---
- hosts: all
  become: True
  roles:
    - { role: ansible-role-mongodb,
        mongodb_net_bindip: '0.0.0.0',
        mongodb_apt_keyserver: 'hkp://keyserver.ubuntu.com:80' }
    - { role: ansible-role-mysql,
        mysql_users: [{
          name: admin,
          password: admin,
          host: '%',
          priv: '*.*:ALL'
        }]}
