Vagrant.configure("2") do |config|

  cpu_percent = "60"
  cpu_count = "2"
  memory = "2048"
  ip_address = "10.2.2.2"

  config.vm.define "dev-db" do |vm_config|
    vm_config.vm.box = "ubuntu/trusty64"

    vm_config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "#{cpu_percent}"]
        vb.cpus = "#{cpu_count}"
        vb.memory = "#{memory}"
    end

    vm_config.vm.hostname = "dev-db"
    vm_config.vm.network :private_network, ip: "#{ip_address}"
    vm_config.vm.network "forwarded_port", guest: 27017, host: 27012 # mongodb
    vm_config.vm.network "forwarded_port", guest: 3306, host: 3306 # mysql

    vm_config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

end
